--- 
:aliases: 
  :instance_method: 
    Object:
      instance_variables: iv
      instance_variable_get: giv
      instance_variable_set: siv
    Module:
      ancestors: an
      instance_methods: im
      private_instance_methods: pim
    Hash:
      select: s
    Array:
      select: s
    Kernel:
      require: r
