---
generated_file: /Users/bozo/.bash/completion/lightning_completions
ignore_paths:
    - .DS_Store
    - .git
commands:
    - name : c
      map_to : cd
      description : my code directories
      paths: 
        - /Users/bozo/code/gems/*
        - /Users/bozo/code/repo/*
        - /Users/bozo/code/repo/priv/*
        - /Users/bozo/code/tds/gems/*
        
    - name : cd-g
      map_to : cd
      paths: gem
      
    - name : pb-g
      map_to : echo -n
      paths: gem
      add_to_command: |pbcopy
      
    - name : m-g
      map_to : mate
      paths: gem
      
    - name : o-g
      map_to : open
      description : open gem's doc in browser
      post_path : /rdoc/index.html
      paths: gem_rdoc
    
    - name : gri
      map_to : ri -d
      description : access ri documentation limited to this gem
      post_path : /ri
      add_to_command: ${@:2}
      paths: gem_rdoc
      completion_regex: ^\S+
    
    - name : v-r
      map_to : vim
      description : ruby core files
      paths: 
      #picked from $LOAD_PATH
        - /Library/Ruby/Site/1.8/**/*.{rb,bundle,so}
        - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/**/*.{rb,bundle,so}
    - name : cd-r
      map_to : cd
      description : ruby core directories
      paths:
         - /Library/Ruby/Site/1.8/**/
         - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/**/
    
    - name : oa
      map_to : open -a
      description : open mac applications
      paths:
        - /Applications/*.app
        - /Applications/Utilities/*.app
        
    - name : v-g
      map_to : vim
      description : open files when in the base directory of a ruby gem project
      paths:
        - lib/**/*.rb
        - test/**/*.rb
        - spec/**/*.rb
        - bin/**
    
    - name : v-rr
      map_to : vim
      description: open files when in the base directory of a rails project
      paths:
        - config/**/*.rb
        - app/**/*.{rb,erb,rhtml}
        - lib/**/*.rb
        - test/**/*.rb
        - spec/**/*.rb

    - name : v-n
      map_to : vim
      description: my notes
      paths:
        - /Users/bozo/docs/notes/**/*.otl
          
paths: 
    #These entries should each map a unique key to a list of directories. When autocompleting, each
    #of the directories will provide the immediate files and directories under them as possible
    #completions. The names of these paths should only be alphanumeric characters ie no special characters.

    # to obtain your own paths to your ruby gems:
    # `gem environment path`.split(":").map {|e| e +"/gems/*" }
    gem:
      - /Users/bozo/.gem/ruby/1.8/gems/*
      - /Library/Ruby/Gems/1.8/gems/*
      - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/*

    gem_rdoc:
      - /Users/bozo/.gem/ruby/1.8/doc/*
      - /Library/Ruby/Gems/1.8/doc/*
      - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/doc/*
