--- 
:aliases: {}

:source_file: /Users/bozo/.bash/completion/lightning_completions
:shell_commands: 
- mate: m
- vim: v
- open: o
- less: l
- grep: g
- git: gi
- echo: e
- cd
- ls
:ignore_paths: 
- .DS_Store
- .git/
:complete_regex: true
:bolts: 
  app: 
    paths: 
    - /Applications/*.app
    - /Applications/Utilities/*.app
    commands: 
    - name: oa
      shell_command: open -a
    alias: a
  code: 
    desc: my code directories
    paths: 
    - /Users/bozo/code/gems/*
    - /Users/bozo/code/repo/*
    - /Users/bozo/code/repo/priv/*
    - /Users/bozo/code/tds/gems/*
    - /Users/bozo/code/fork/*
    commands: 
    - name: c
      shell_command: cd
    aliases: 
      mc: /Users/bozo/code/gems/my_core
    alias: c
  system_ruby_dir: 
    paths: 
    - /Library/Ruby/Site/1.8/**/
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/**/
    aliases: 
      r1: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8
    alias: rd
  wild: 
    paths: 
    - "**/*"
    alias: w
  local_ruby: 
    desc: base directory of a ruby gem project
    paths: 
    - "**/*.rb"
    - bin/**
    alias: rb
  ruby_test:
    desc: base directory of a ruby gem project
    paths: 
    - test/**/*_test.rb
    - spec/**/*.spec
    commands:
    - name: tt
      shell_command: testrb
    - name: sp
      shell_command: spec
  gem: 
    paths: 
    - /Users/bozo/.gem/ruby/1.8/gems/*
    - /Library/Ruby/Gems/1.8/gems/*
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/*
    commands: 
    - name: pb-g
      add_to_command: " |pbcopy"
      shell_command: echo -n
    aliases: 
      g2: /Users/bozo/.gem/ruby/1.8/gems
      g3: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems
      g1: /Library/Ruby/Gems/1.8/gems
    alias: g
  code_world: 
    paths: 
    - /Users/bozo/code/world/*
    alias: cw
  notes: 
    paths: 
    - /Users/bozo/docs/notes/**/*.otl
    alias: n
  wild_dir: 
    paths: 
    - "**/"
    alias: wd
  bin: 
    alias: b
    paths: 
    - /Users/bozo/.rvm/bin/*
    - /usr/bin/*
    - /bin/*
    - /usr/sbin/*
    - /sbin/*
    - /usr/local/bin/*
    - /usr/X11/bin/*
    - /usr/local/git/bin/*
    - /opt/local/bin/*
    - /opt/local/sbin/*
    - /usr/local/mysql/bin/*
    - /Users/bozo/bin/*
    - /Users/bozo/.rip/active/bin/*
  gem_doc: 
    paths: 
    - /Users/bozo/.gem/ruby/1.8/doc/*
    - /Library/Ruby/Gems/1.8/doc/*
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/doc/*
    commands: 
    - post_path: /rdoc/index.html
      desc: open gem's doc in browser
      shell_command: open
    - post_path: /ri
      desc: access ri documentation limited to this gem
      shell_command: ri --no-standard-docs -d
    alias: gd
  ruby19_files: 
    paths: 
    - /Users/bozo/.rvm/ruby-1.9.1-p243/lib/ruby/**/*.{rb,bundle,so,c}
    alias: r9
  ror: 
    desc: access any files from the root of a rails project
    paths: 
    - "{app,config}/**/*.{erb,rhtml,yaml,yml}"
    - "**/*.rb"
  system_ruby_file: 
    paths: 
    - /Library/Ruby/Site/1.8/**/*.{rb,bundle,so,c}
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/**/*.{rb,bundle,so,c}
    alias: r
