--- 
:complete_regex: true
:bolts: 
  ruby_test: 
    desc: base directory of a ruby gem project
    paths: 
    - test/**/*_test.rb
    - spec/**/*.spec
    commands: 
    - name: ba
      shell_command: bacon -Ilib
    - name: tt
      shell_command: testrb
    - name: sp
      shell_command: spec
  app: 
    paths: 
    - /Applications/*.app
    - /Applications/Utilities/*.app
    commands: 
    - name: oa
      shell_command: open -a
    alias: a
  system_ruby_dir: 
    paths: 
    - /Library/Ruby/Site/1.8/**/
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/**/
    aliases: 
      r1: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8
    alias: rd
  code: 
    desc: my code directories
    paths: 
    - /Users/bozo/code/gems/*
    - /Users/bozo/code/repo/*
    - /Users/bozo/code/repo/priv/*
    - /Users/bozo/code/tds/gems/*
    - /Users/bozo/code/fork/*
    aliases: 
      mc: /Users/bozo/code/gems/my_core
    commands: 
    - name: c
      shell_command: cd
    alias: c
  ruby_load_path: 
    :paths: 
    - /Users/bozo/.rip/active/lib/**/*.rb
    - /Library/Ruby/Site/1.8/**/*.rb
    - /Library/Ruby/Site/1.8/powerpc-darwin9.0/**/*.rb
    - /Library/Ruby/Site/1.8/universal-darwin9.0/**/*.rb
    - /Library/Ruby/Site/**/*.rb
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/**/*.rb
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/powerpc-darwin9.0/**/*.rb
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin9.0/**/*.rb
  local_ruby: 
    desc: base directory of a ruby gem project
    paths: 
    - "**/*.rb"
    - bin/**
    alias: rb
  wild: 
    paths: 
    - "**/*"
    alias: w
  code_world: 
    paths: 
    - /Users/bozo/code/world/*
    alias: cw
  gem: 
    paths: 
    - /Users/bozo/.gem/ruby/1.8/gems/*
    - /Library/Ruby/Gems/1.8/gems/*
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/*
    aliases: 
      g2: /Users/bozo/.gem/ruby/1.8/gems
      g3: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems
      g1: /Library/Ruby/Gems/1.8/gems
    alias: g
    add_commands: 
    - name: pb-g
      add_to_command: " |pbcopy"
      shell_command: echo -n
  notes: 
    paths: 
    - /Users/bozo/docs/notes/**/*.otl
    alias: n
  wild_dir: 
    paths: 
    - "**/"
    alias: wd
  bin: 
    paths: 
    - /Users/bozo/.rvm/bin/*
    - /usr/bin/*
    - /bin/*
    - /usr/sbin/*
    - /sbin/*
    - /usr/local/bin/*
    - /usr/X11/bin/*
    - /usr/local/git/bin/*
    - /opt/local/bin/*
    - /opt/local/sbin/*
    - /usr/local/mysql/bin/*
    - /Users/bozo/bin/*
    - /Users/bozo/.rip/active/bin/*
    alias: b
  ruby19_files: 
    paths: 
    - /Users/bozo/.rvm/ruby-1.9.1-p243/lib/ruby/**/*.{rb,bundle,so,c}
    alias: r9
  gem_doc: 
    paths: 
    - /Users/bozo/.gem/ruby/1.8/doc/*
    - /Library/Ruby/Gems/1.8/doc/*
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/doc/*
    commands: 
    - post_path: /rdoc/index.html
      shell_command: open
      desc: open gem's doc in browser
    - post_path: /ri
      shell_command: ri --no-standard-docs -d
      desc: access ri documentation limited to this gem
    alias: gd
  system_ruby_file: 
    paths: 
    - /Library/Ruby/Site/1.8/**/*.{rb,bundle,so,c}
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/**/*.{rb,bundle,so,c}
    alias: r
  ror: 
    desc: access any files from the root of a rails project
    paths: 
    - "{app,config}/**/*.{erb,rhtml,yaml,yml}"
    - "**/*.rb"
:shell_commands: 
  cd: cd
  cp: cp
  grep: g
  vim: v
  ls: ls
  git: gi
  less: l
  echo: e
  mate: m
  open: o

:ignore_paths: 
- .DS_Store
- .git/
