--- 
:complete_regex: true
:bolts: 
  app: 
    paths: 
    - /Applications/*.app
    - /Applications/Utilities/*.app
    commands: 
    - name: oa
      shell_command: open -a
    alias: a
  ruby_test: 
    desc: base directory of a ruby gem project
    paths: 
    - test/**/*_test.rb
    - spec/**/*.spec
    commands: 
    - name: ba
      shell_command: bacon -Ilib
    - name: tt
      shell_command: testrb
    - echo
    - vim
    alias: rt
  code: 
    desc: my code directories
    paths: 
    - /Users/bozo/code/gems/*
    - /Users/bozo/code/repo/*
    - /Users/bozo/code/repo/priv/*
    - /Users/bozo/code/tds/gems/*
    - /Users/bozo/code/fork/*
    commands: 
    - name: c
      shell_command: cd
    - mate
    - echo
    alias: c
  wild: 
    paths: 
    - "**/*"
    alias: w
    add_commands:
    - git
  local_ruby: 
    desc: base directory of a ruby gem project
    paths: 
    - "**/*.rb"
    - bin/**
    add_commands:
    - git
    alias: rb
  ruby_load_path: 
    :paths: 
    - /Users/bozo/.rip/active/lib/**/*.rb
    - /Library/Ruby/Site/1.8/**/*.rb
    - /Library/Ruby/Site/1.8/powerpc-darwin9.0/**/*.rb
    - /Library/Ruby/Site/1.8/universal-darwin9.0/**/*.rb
    - /Library/Ruby/Site/**/*.rb
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/**/*.rb
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/powerpc-darwin9.0/**/*.rb
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin9.0/**/*.rb
    commands:
    - less
    - echo
    alias: rlp
  gem: 
    paths: 
    - /Users/bozo/.gem/ruby/1.8/gems/*
    - /Library/Ruby/Gems/1.8/gems/*
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/*
    aliases: 
      g2: /Users/bozo/.gem/ruby/1.8/gems
      g3: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems
      g1: /Library/Ruby/Gems/1.8/gems
    alias: g
    add_commands: 
    - name: pb-g
      add_to_command: " |pbcopy"
      shell_command: echo -n
  code_world: 
    paths: 
    - /Users/bozo/code/world/*
    alias: cw
    commands:
    - echo
    - mate
    - cd
    - less
  notes: 
    paths: 
    - /Users/bozo/docs/notes/**/*.otl
    commands: 
    - vim
    - less
    alias: n
  wild_dir: 
    paths: 
    - "**/"
    alias: wd
    commands:
    - ls
    - cd
    - echo
  ruby_19: 
    :paths: 
    - /Users/bozo/.rvm/ruby-1.9.1-p378/lib/ruby/1.9.1/**/*.{rb,bundle,so,c}
    - /Users/bozo/.rvm/ruby-1.9.1-p378/lib/ruby/site_ruby/1.9.1/**/*.{rb,bundle,so,c}
    alias: r9
  bin: 
    paths: 
    - /Users/bozo/.rvm/bin/*
    - /usr/bin/*
    - /bin/*
    - /usr/sbin/*
    - /sbin/*
    - /usr/local/bin/*
    - /usr/X11/bin/*
    - /usr/local/git/bin/*
    - /opt/local/bin/*
    - /opt/local/sbin/*
    - /usr/local/mysql/bin/*
    - /Users/bozo/bin/*
    - /Users/bozo/.rip/active/bin/*
    commands: 
    - less
    alias: b
  gem_doc: 
    paths: 
    - /Users/bozo/.gem/ruby/1.8/doc/*
    - /Library/Ruby/Gems/1.8/doc/*
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/doc/*
    commands: 
    - post_path: /rdoc/index.html
      desc: open gem's doc in browser
      shell_command: open
      name: o-gd
    - post_path: /ri
      desc: access ri documentation limited to this gem
      shell_command: ri --no-standard-docs -d
    alias: gd
  ruby: 
    paths: 
    - /Library/Ruby/Site/1.8/**/*.{rb,bundle,so,c}
    - /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/**/*.{rb,bundle,so,c}
    alias: r
  ror: 
    desc: access any files from the root of a rails project
    paths: 
    - "{app,config,lib}/**/*"
    - "{db}/**/*.rb"
    commands: 
    - echo
    - grep
    - vim
:ignore_paths: 
- .DS_Store
- .git/
:shell_commands: 
  cd: cd
  cp: cp
  vim: v
  grep: g
  less: l
  ls: ls
  mate: m
  echo: e
