---
:gems :
  thor : 
    - ~/code/fork/thor/lib
    - ~/code/fork/thor/bin
  alias : ~/code/gems/alias/lib
  boson : ~/code/gems/boson/lib
  core : ~/code/gems/core/lib
  my_core : ~/code/gems/my_core/lib
  lightning :
    - ~/code/gems/lightning/lib
    - ~/code/gems/lightning/bin
  hirb: ~/code/gems/hirb/lib
  jeweler: ~/code/fork/jeweler/lib
